### ISSUE TITLE
Commas as decimal cause wrong conversion

### ISSUE THREAD

**Issue by semrola** [EdFage/fuelCostCalculator#25]
In my locale, comma is used for separating decimal numbers. If the distance has a decimal number, the number will not be correctly parsed from the string. It just takes the whole number, without decimals, so the price is not calculated correctly. Check image for reference.
[Image](https://i.imgur.com/x37oYeG.png)

**Comment by EdFage** [comment]
Hey @semrola, thank you for raising this, I will get to it when I have the chance, hopefully tomorrow.

**Comment by EdFage** [comment]
The issue is solved, the new version is awaiting approval on the chromestore and should be live in a few day's time. Let me know if you have further issues!
